backend_apps/access/urls.py
from django.conf.urls import url

from .views import change_password
from .views import (logout_view, login_view)

urlpatterns = [
    # url(r'^registro/$',
    #     RegistroCreateView.as_view(), name='register'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),

    url(r'^password/$', change_password, name='change_password'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from backend_apps.access.views import dashboard

from django.conf.urls.static import static
from qr_code import urls as qr_code_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),

    # Backend

    url(r'^backend/', include('backend_apps.backend_auth.urls', namespace='backend')),
    url(r'^access/', include('backend_apps.access.urls', namespace='access')),

    url(r'^$', dashboard, name='dashboard'),

    # My Apps
    url(r'^almacen/', include('apps.almacen.urls', namespace='almacen')),
    url(r'^compra/', include('apps.compra.urls', namespace='compra')),
    url(r'^persona/', include('apps.persona.urls', namespace='persona')),
    url(r'^producto/', include('apps.producto.urls', namespace='producto')),
    url(r'^sunat/', include('apps.sunat.urls', namespace='sunat')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^vendedor/', include('apps.vendedor.urls', namespace='vendedor')),
    url(r'^venta/', include('apps.venta.urls', namespace='venta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_apps/access/models.py
from django.db import models

# Create your models here.

backend_apps/access/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        # user_qs = User.objects.filter(username=username)
        # if user_qs.count() == 1:
        #     user = user_qs.first()
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect passsword")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)

backend_apps/access/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User, Group
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    update_session_auth_hash)
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView
from django.shortcuts import redirect, render
# from ..forms.RegistroForm import RegistroForm
from .forms import UserLoginForm


@login_required
def logout_view(request):
    logout(request)
    return redirect("/")


def login_view(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        # Roles estaticos estudiante y administrador

        # return redirect("/dashboard")
        return redirect("/")

    return render(request, "access/login.html", {"form": form, "title": title})


def home(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)

    return render(request, "access/home.html", {'form': form})


@login_required
def dashboard(request):
    return render(request, "access/dashboard.html")


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Su contraseña fue cambiada satisfactoriamente!')
            return redirect('access:change_password')
        else:
            messages.error(request, 'Corrija por favor el error abajo.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'access/change_password.html', {
        'form': form
    })

backend_apps/access/templates/access/change_password.html
{% extends "base/base_back.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>

{% endblock content %}

backend_apps/access/templates/access/dashboard.html
{% extends "base/base_back.html" %}
{% load i18n staticfiles crispy_forms_tags %}


{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
{% endblock breadcrumbs %}

{% block content %}

    <h1>Sistema de Control Interno</h1>

{% endblock content %}

backend_apps/access/templates/access/home.html
{% extends "base/base_back.html" %}
{% load i18n staticfiles crispy_forms_tags %}

{% block content %}
<!-- Nav tabs -->
<!-- Tab panes -->
<section id="login_bg">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <div id="login">
                    <p class="text-center">
                        <img src="" width="60px" alt="">
                    </p>
                    <hr>
                    <form action="{% url 'access:login' %}" enctype="multipart/form-data"
                          method="post">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <button type="submit" class="button_fullwidth">Ingreso</button>


                        <a href="{# url 'cuenta:register' #}" id="registesr"
                           class="button_fullwidth">
                            Crear Cuenta
                        </a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section> <!-- End login -->

{% endblock content %}

{% block customjs %}
<script>
    $(function () {

        $('#login-form-link').click(function (e) {
            $("#login-form").delay(100).fadeIn(100);
            $("#register-form").fadeOut(100);
            $('#register-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
        $('#register-form-link').click(function (e) {
            $("#register-form").delay(100).fadeIn(100);
            $("#login-form").fadeOut(100);
            $('#login-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });

    });
</script>
{% endblock customjs %}

backend_apps/access/templates/access/login.html
{% extends "base/base_back.html" %}
{% load i18n staticfiles crispy_forms_tags %}



{% block content %}



    <!-- Nav tabs -->

    <!-- Tab panes -->



    <section id="login_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                    <div id="login">
                        <p class="text-center">
                            <img src="" width="60px" alt="">
                        </p>
                        <hr>
                        <form action="{% url 'access:login' %}" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}

                            <button type="submit" class="button_fullwidth">Ingreso</button>


                            <a href="{# url 'cuenta:register' #}" id="registesr" class="button_fullwidth">
                                Crear Cuenta
                            </a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- End login -->






{% endblock content %}

{% block customjs %}
    <script>
        $(function () {

            $('#login-form-link').click(function (e) {
                $("#login-form").delay(100).fadeIn(100);
                $("#register-form").fadeOut(100);
                $('#register-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });
            $('#register-form-link').click(function (e) {
                $("#register-form").delay(100).fadeIn(100);
                $("#login-form").fadeOut(100);
                $('#login-form-link').removeClass('active');
                $(this).addClass('active');
                e.preventDefault();
            });

        });
    </script>
{% endblock customjs %}