backend_apps/backend_auth/urls.py
from django.conf.urls import url

from .views.group import GroupListView, GroupCretaView, GroupUpdateView, GroupDeleteView
from .views.menu import MenuUpdateActiveView, MenuUpdateView, MenuDeleteView
from .views.user import UserCreateView, UserUpdateView, UserDeleteView
from .views.group_permission import GroupPermissionsUpdateView

from .views.user import (UserListView)
from .views.menu import (MenuListView, MenuCreateView)
from .views.permission import (PermissionCreateView, PermissionDeleteView, PermissionListView,
                               PermissionUpdateView)

urlpatterns = [

    # User
    url(r'^user/list/$', UserListView.as_view(), name='user_list'),
    url(r'^user/add/$', UserCreateView.as_view(), name='user_add'),
    url(r'^user/update/(?P<pk>[^/]+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'^user/delete/(?P<pk>[^/]+)/$', UserDeleteView.as_view(), name='user_delete'),

    url(r'^group/list/$', GroupListView.as_view(), name='group_list'),
    url(r'^group/add/$', GroupCretaView.as_view(), name='group_add'),
    url(r'^group/update/(?P<pk>[^/]+)/$', GroupUpdateView.as_view(), name='group_update'),
    url(r'^group/delete/(?P<pk>[^/]+)/$', GroupDeleteView.as_view(), name='group_delete'),
    url(r'^grouppermissions/update/$', GroupPermissionsUpdateView.as_view(), name='group_permissions_update'),

    # Menu
    url(r'^menu/list/$', MenuListView.as_view(), name='menu_list'),
    url(r'^menu/add/$', MenuCreateView.as_view(), name='menu_add'),
    url(r'^menu/state/(?P<state>[\w\d\-]+)/(?P<pk>[^/]+)/$',
        MenuUpdateActiveView.as_view(), name='menu_state'),
    url(r'^menu/update/(?P<pk>[^/]+)/$', MenuUpdateView.as_view(), name='menu_update'),
    url(r'^menu/delete/(?P<pk>[^/]+)/$', MenuDeleteView.as_view(), name='menu_delete'),

    #
    url(r'^permission/delete/(?P<pk>.*)/$',
        PermissionDeleteView.as_view(), name='permission_delete'),  # x pony
    url(r'^permission/update/(?P<pk>.*)/$',
        PermissionUpdateView.as_view(), name='permission_update'),
    url(r'^permission/add/$',
        PermissionCreateView.as_view(), name='permission_add'),
    url(r'^permission/list/$',
        PermissionListView.as_view(), name='permission_list'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from backend_apps.access.views import dashboard

from django.conf.urls.static import static
from qr_code import urls as qr_code_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),

    # Backend

    url(r'^backend/', include('backend_apps.backend_auth.urls', namespace='backend')),
    url(r'^access/', include('backend_apps.access.urls', namespace='access')),

    url(r'^$', dashboard, name='dashboard'),

    # My Apps
    url(r'^almacen/', include('apps.almacen.urls', namespace='almacen')),
    url(r'^compra/', include('apps.compra.urls', namespace='compra')),
    url(r'^persona/', include('apps.persona.urls', namespace='persona')),
    url(r'^producto/', include('apps.producto.urls', namespace='producto')),
    url(r'^sunat/', include('apps.sunat.urls', namespace='sunat')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^vendedor/', include('apps.vendedor.urls', namespace='vendedor')),
    url(r'^venta/', include('apps.venta.urls', namespace='venta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_apps/backend_auth/forms/group.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Div, Field

from django import forms
from django.contrib.auth.models import Group

from backend_apps.utils.forms import smtSave, btnCancel, btnReset


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = ('',)

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'js-validate form-vertical'
        self.helper.layout = Layout(
            Row(
                Div(
                    Field('name', css_class='input-required'), css_class='col-md-12'
                )
            ),
            Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ),
        )

backend_apps/backend_auth/forms/menu.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Div, Row, HTML
from crispy_forms.bootstrap import FormActions, TabHolder, Tab
from backend_apps.utils.forms import smtSave, btnCancel, btnReset

from ..models import Menu


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        exclude = ("is_active",)

    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        self.fields['title'].help_text = u'<small class="help-error"></small> %s' % _(
            u' ')
        self.fields['pos'].help_text = u'<small class="help-error"></small> %s' % _(
            u' ')
        self.fields['url'].help_text = u'<small class="help-error"></small> %s' % _(
            u' ')
        self.fields['parent'].queryset = Menu.objects.filter(parent=None)

        self.fields['permission'].label_from_instance = lambda obj: "%s/%s" % (
            obj.content_type.app_label, obj.codename)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'js-validate form-vertical'
        self.helper.layout = Layout(
            Row(
                Div(Field('title', css_class='input-required'),
                    css_class='col-md-4'),
                Div(Field('parent', ),
                    css_class='col-md-4'),
                Div(Field('permission', ),
                    css_class='col-md-4'),
            ),
            Row(
                Div(Field('pos', css_class='input-required input-integer mask-pint'),
                    css_class='col-md-4'),
                Div(Field('icon', ),
                    css_class='col-md-4'),
                Div(Field('url', css_class='input-required'),
                    css_class='col-md-4'),
            ),
            Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ),
        )

backend_apps/backend_auth/views/group.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import BaseDeleteView
from django.utils.encoding import force_text
from ..forms.group import GroupForm
from backend_apps.utils.decorators import permission_resource_required
from backend_apps.utils.forms import empty
from backend_apps.utils.security import get_dep_objects



class GroupListView(ListView):
    model = Group
    paginate_by = settings.PER_PAGE
    template_name = "auths/group/list.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupListView, self).dispatch(request, *args, **kwargs)

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'name')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = ('Seleccione %s para Cambiar') % ('Grupo')

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')
        return context


class GroupCretaView(CreateView):
    model = Group
    form_class = GroupForm
    template_name = "auths/group/form.html"
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupCretaView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupCretaView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = "Agregar Menu"
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = 'El %(name)s "%(obj)s" fue agregado satisfactoriamente' % {
            'name': self.model._meta.verbose_name,
            'obj': self.object
        }

        if self.object.id:
            messages.success(self.request, msg)
        return super(GroupCretaView, self).form_valid(form)


class GroupUpdateView(UpdateView):
    model = Group
    form_class = GroupForm
    template_name = "auths/group/form.html"
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        if not pk:
            return HttpResponseRedirect(self.success_url)
        self.kwargs['pk'] = pk
        try:
            self.get_object()
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(self.success_url)
        return super(GroupUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = "Cambiar %s" % "Grupo"
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = 'El %(name)s "%(obj)s" fue cambiado satisfactoriamente' % {
            'name': self.model._meta.verbose_name,
            'obj': self.object
        }
        messages.success(self.request, msg)
        return super(GroupUpdateView, self).form_valid(form)


class GroupDeleteView(BaseDeleteView):
    model = Group
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        if not pk:
            return HttpResponseRedirect(self.success_url)
        self.kwargs['pk'] = pk
        try:
            self.get_object()
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(self.success_url)
        return super(GroupDeleteView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        try:
            d = self.get_object()
            deps, msg = get_dep_objects(d)
            if deps:
                messages.warning(self.request, ('No se puede eliminar %(name)s') % {
                    "name": self.model._meta.verbose_name + ' "' + force_text(d) + '"'
                })
                raise Exception(msg)

            d.delete()
            msg = 'The %(name)s "%(obj)s" was deleted successfully.' % {
                'name': self.model._meta.verbose_name,
                'obj': d
            }
            if not d.id:
                messages.success(self.request, msg)

        except Exception as e:
            messages.error(request, e)

        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

backend_apps/backend_auth/views/group_permission.py
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.models import Permission, Group
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

from backend_apps.utils.forms import empty

from backend_apps.utils.decorators import permission_resource_required


class GroupPermissionsUpdateView(ListView):

    """ """
    model = Permission
    # grouppermissions es el controller
    template_name = 'auths/group/group_permission_form.html'
    success_url = reverse_lazy('backend:group_permissions_update')

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupPermissionsUpdateView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'name')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)
        # return self.model.objects.all().order_by("content_type__app_label",
        # "content_type__model")

    def get_context_data(self, **kwargs):
        try:
            group_list = Group.objects.all().order_by('-id')
            # obtener los permissions del group para mostrarlos
            privilegios = []
            for g in group_list:
                for p in g.permissions.all():
                    privilegios.append('%s-%s' % (p.id, g.id))
        except Exception as e:
            messages.error(self.request, e)

        context = super(
            GroupPermissionsUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grouppermissions'
        context['title'] = 'Selccione %s para modificar' % ('permissions')

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')

        context['group_list'] = group_list
        context['privilegios'] = privilegios
        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        try:
            sid = transaction.savepoint()
            '''
            group_list = Group.objects.all().order_by('-id')
            old_privilegios_r = []
            for g in group_list:
                for p in g.permissions.all():
                    old_privilegios_r.append('%s-%s' % (p.id, g.id))
            '''
            old_privilegios_r = request.POST.get('old_privilegios')
            if old_privilegios_r:
                old_privilegios_r = old_privilegios_r.split(',')

            # Elimino los antiguos privilegios
            for value in old_privilegios_r:
                # el formato es 1-4 = recurso_id-perfil_id
                data = value.split('-')
                group = Group.objects.get(id=data[1])
                recur = Permission.objects.get(id=data[0])
                group.permissions.remove(recur)

            privilegios_r = request.POST.getlist('privilegios')
            for value in privilegios_r:
                # el formato es 1-4 = recurso_id-perfil_id
                data = value.split('-')
                group = Group.objects.get(id=data[1])
                recur = Permission.objects.get(id=data[0])
                group.permissions.add(recur)
            msg = 'El %(name)s "%(obj)s" fue cambiado satisfactoriamente.' % {
                'name': '',
                'obj': 'permissions'
            }
            messages.success(self.request, msg)
        except Exception as e:
            transaction.savepoint_rollback(sid)
            messages.error(self.request, e)

        return HttpResponseRedirect(self.success_url)

backend_apps/backend_auth/templates/auths/permission/form.html
{% extends "base/base_back.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Create/Update permission
-->
{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
<a href="">{% trans 'Home' %}</a>
&rsaquo;
<a href="{% url 'backend:permission_list' %}">{{opts.verbose_name_plural|capfirst}}</a>
&rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
{{ opts.verbose_name|capfirst }} | <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

{% crispy form %}

{% endblock %}

{% block extrajs %}
{{ block.super }}

<script type="text/javascript">

</script>
{% endblock extrajs %}

backend_apps/backend_auth/templates/auths/permission/list.html
{% extends "base/base_back.html" %}
<!--
@copyright   Copyright (c) 2014 Submit Consulting
@author      Angel Sullon (@asullom)
@package     sad

Descripcion: Lista permission
-->
{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
    <a href="">{% trans 'Home' %}</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
    <script type="text/javascript">
        $(function () {
            $('table').kgrid({
                form_data: ['{{f}}', '{{q}}'],
                form_to: '{% url "backend:permission_list" %}?f={{f}}&q={{q}}',
                order_attr: 'class=""',
                form_to: '{% url "backend:permission_list" %}?f={{f}}&q={{q}}',
            });
        });
    </script>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <a href="{% url 'backend:permission_add' %}" class="btn btn-primary text-bold"
                   title="{% trans 'Add' %} {% trans 'permission' %}"><i class="fa fa-plus"></i> <span
                        class="hidden-xs"> {% trans 'Add' %}</span></a>
            </div>
        </div>
    </div>
    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>#</th>
                <th class="col-hidden" data-search="content_type__app_label"
                    data-order="content_type__app_label">{% trans 'App'|capfirst %}</th>
                <th class="col-hidden" data-search="codename" data-order="codename">{% trans 'Code' %}
                    (APP.CONTROLADOR_ACCION)
                </th>
                <th class="col-hidden" data-search="name" data-order="name">{% trans 'Detail' %}</th>
                <th class="btn-actions col-blocked text-center">{% trans 'Action' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for d in object_list %}
                <tr>
                    <td>{% if is_paginated %}
                        {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                        {{ forloop.counter }}
                    {% endif %}
                    </td>
                    <td>{{ d.content_type.app_label }} {{ d.id }} </td>
                    <td>{{ d.codename }} </td>
                    <td>{{ d.name }} </td>

                    <td class="text-center">
                        <div class="btn-group">
                            <a href="{% url 'backend:permission_update' d.pk|key:'permission_upd' %}"
                               class="btn btn-info btn-sm text-bold"
                               title="{% trans 'Change' %} {% trans 'permission' %}" rel="tooltip"><i
                                    class="btn-icon-only fa fa-edit"></i></a>

                            <a href="{% url 'backend:permission_delete' d.pk %}"
                               class="btn btn-danger btn-sm js-confirm text-bold"
                               msg-title="{% trans 'Delete' %} {% trans 'permission' %}?."
                               msg="{% trans 'Are you sure?' %}<br/>{% trans 'Remember that this operation can not be reversed.' %}"
                               title="{% trans 'Delete' %} {% trans 'permission' %}" rel="tooltip"><i
                                    class="btn-icon-only fa fa-trash-o"></i></a>

                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="row">
        {% if is_paginated %}
            {% load paginator %}
            {% paginator %}
        {% else %}
            <div class="col-md-12">
                <ul class="breadcrumbpag">
                    {{ object_list.count }} {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}
                    {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
                </ul>
            </div>
        {% endif %}
    </div>

{% endblock content %}