apps/almacen/urls.py
from django.conf.urls import url

from .views.arqueo import ArqueoSalidaListView, ArqueoListView, ArqueoSalidaDetailView, ArqueoSalidaEquipoUpdateView, \
    ArqueoSalidaCerrar
from .views.compra import ComprobanteListView, CompraDetailView, ComprobanteEstadoUpdateView
from .views.compra_detalle import CompraDetalleDetailView, CompraDetalleServiceView
from .views.equipo import EquiposAddServicioView, EquipoJson, EquipoMenuListView, \
    EquipoUpdateView, EquipoDetailView, EquipoDeleteView
from .views.usuario import UserDetailView
from .views.salida import SalidaCreateTemplateView, SalidaDetailView
from .views.producto import ProductoListView, ProductoDetailView, ProductoDetailCountAlmacenServiceView

urlpatterns = [

    # Menu
    url(r"^compra/listar$", ComprobanteListView.as_view(), name='compra_list'),
    url(r"^arqueo/listar$", ArqueoListView.as_view(), name='arqueo_list'),
    url(r"^salida/crear$", SalidaCreateTemplateView.as_view(), name='salida_add'),
    url(r"^producto/listar$", ProductoListView.as_view(), name='producto_list'),
    url(r"^equipo/listar$", EquipoMenuListView.as_view(), name='equipo_list_menu'),

    # Utils

    url(r"^usuario/detallar/(?P<pk>[^/]+)$", UserDetailView.as_view(), name='user_detail'),
    url(r"^salida/detallar/(?P<pk>[^/]+)$", SalidaDetailView.as_view(), name='salida_detail'),
    url(r"^producto/detallar/(?P<pk>[^/]+)$", ProductoDetailView.as_view(), name='producto_detail'),

    # administracion de equipo
    url(r"^equipo/detail/(?P<pk>[^/]+)$", EquipoDetailView.as_view(), name='equipo_detail'),
    url(r"^equipo/eliminar/(?P<pk>[^/]+)$", EquipoDeleteView.as_view(), name='equipo_delete'),
    url(r"^equipo/actualizar/(?P<pk>[^/]+)$", EquipoUpdateView.as_view(), name='equipo_update'),

    # compra
    url(r"^compra_detalle/detallar/(?P<pk>[^/]+)/(?P<producto_pk>[^/]+)$", CompraDetalleDetailView.as_view(),
        name='compra_detalle_detail'),
    url(r"^compra/detallar/(?P<pk>[^/]+)$", CompraDetailView.as_view(), name='compra_detail'),
    url(r"^compra/update_status/(?P<pk>[^/]+)$", ComprobanteEstadoUpdateView.as_view(), name='compra_updatestatus'),
    url(r"^compra_detalle/detailjson/$", CompraDetalleServiceView.as_view(), name='comra_detalle_detail_json'),

    # Arqueo
    url(r"^arqueo_salida/listar/(?P<user_pk>[^/]+)$", ArqueoSalidaListView.as_view(), name='arqueo_salida_list'),
    url(r"^arqueo_salida/detallar/(?P<salida_pk>[^/]+)$", ArqueoSalidaDetailView.as_view(),
        name='arqueo_salida_detail'),
    url(r"^arqueo_salida/cerrar/(?P<salida_pk>[^/]+)$", ArqueoSalidaCerrar.as_view(), name='arqueo_salida_close'),
    url(r"^arqueo_salida/equipo/(?P<salida_detalle_pk>[^/]+)$", ArqueoSalidaEquipoUpdateView.as_view(),
        name='arqueo_equipo_update'),

    # Service
    url(r"^equipo/add_service$", EquiposAddServicioView.as_view(), name='equipo_addservice'),
    url(r"^equipo/detail_json$", EquipoJson.as_view(), name='equipo_detail_json'),
    url(r"^producto/almacen_contar/(?P<pk>[^/]+)$", ProductoDetailCountAlmacenServiceView.as_view(),
        name='producto_detailservice'),

]

backend_apps/backend_auth/urls.py
from django.conf.urls import url

from .views.group import GroupListView, GroupCretaView, GroupUpdateView, GroupDeleteView
from .views.menu import MenuUpdateActiveView, MenuUpdateView, MenuDeleteView
from .views.user import UserCreateView, UserUpdateView, UserDeleteView
from .views.group_permission import GroupPermissionsUpdateView

from .views.user import (UserListView)
from .views.menu import (MenuListView, MenuCreateView)
from .views.permission import (PermissionCreateView, PermissionDeleteView, PermissionListView,
                               PermissionUpdateView)

urlpatterns = [

    # User
    url(r'^user/list/$', UserListView.as_view(), name='user_list'),
    url(r'^user/add/$', UserCreateView.as_view(), name='user_add'),
    url(r'^user/update/(?P<pk>[^/]+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'^user/delete/(?P<pk>[^/]+)/$', UserDeleteView.as_view(), name='user_delete'),

    url(r'^group/list/$', GroupListView.as_view(), name='group_list'),
    url(r'^group/add/$', GroupCretaView.as_view(), name='group_add'),
    url(r'^group/update/(?P<pk>[^/]+)/$', GroupUpdateView.as_view(), name='group_update'),
    url(r'^group/delete/(?P<pk>[^/]+)/$', GroupDeleteView.as_view(), name='group_delete'),
    url(r'^grouppermissions/update/$', GroupPermissionsUpdateView.as_view(), name='group_permissions_update'),

    # Menu
    url(r'^menu/list/$', MenuListView.as_view(), name='menu_list'),
    url(r'^menu/add/$', MenuCreateView.as_view(), name='menu_add'),
    url(r'^menu/state/(?P<state>[\w\d\-]+)/(?P<pk>[^/]+)/$',
        MenuUpdateActiveView.as_view(), name='menu_state'),
    url(r'^menu/update/(?P<pk>[^/]+)/$', MenuUpdateView.as_view(), name='menu_update'),
    url(r'^menu/delete/(?P<pk>[^/]+)/$', MenuDeleteView.as_view(), name='menu_delete'),

    #
    url(r'^permission/delete/(?P<pk>.*)/$',
        PermissionDeleteView.as_view(), name='permission_delete'),  # x pony
    url(r'^permission/update/(?P<pk>.*)/$',
        PermissionUpdateView.as_view(), name='permission_update'),
    url(r'^permission/add/$',
        PermissionCreateView.as_view(), name='permission_add'),
    url(r'^permission/list/$',
        PermissionListView.as_view(), name='permission_list'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from backend_apps.access.views import dashboard

from django.conf.urls.static import static
from qr_code import urls as qr_code_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),

    # Backend

    url(r'^backend/', include('backend_apps.backend_auth.urls', namespace='backend')),
    url(r'^access/', include('backend_apps.access.urls', namespace='access')),

    url(r'^$', dashboard, name='dashboard'),

    # My Apps
    url(r'^almacen/', include('apps.almacen.urls', namespace='almacen')),
    url(r'^compra/', include('apps.compra.urls', namespace='compra')),
    url(r'^persona/', include('apps.persona.urls', namespace='persona')),
    url(r'^producto/', include('apps.producto.urls', namespace='producto')),
    url(r'^sunat/', include('apps.sunat.urls', namespace='sunat')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^vendedor/', include('apps.vendedor.urls', namespace='vendedor')),
    url(r'^venta/', include('apps.venta.urls', namespace='venta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/almacen/views/arqueo.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, TemplateView
from django.views.generic.base import View

from apps.almacen.constants import SALIDA
from apps.almacen.models.equipo import Equipo
from apps.almacen.models.salida import Salida
from apps.almacen.models.salida_detalle import SalidaDetalle
from backend_apps.backend_auth.constants import VENTA, DISTRIBUIDOR, ALMACEN
from backend_apps.backend_auth.models import User
from backend_apps.utils.decorators import permission_resource_required


class ArqueoListView(ListView):
    u"""User List para arqueo"""
    model = User
    template_name = "almacen/arqueo/user_list.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        q = self.model.objects.filter(groups__name=DISTRIBUIDOR)

        return q

    def get_context_data(self, **kwargs):
        context = super(ArqueoListView, self).get_context_data(**kwargs)

        context['opts'] = self.model._meta
        context['cmi'] = 'Usuarios'
        context['title'] = 'Seleccione %s para agregar equipos' % 'Usuario'
        return context


class ArqueoSalidaListView(ListView):
    u"""Arque de de Equipos"""
    model = Salida
    template_name = "almacen/arqueo/salida_list.html"

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        print(self.kwargs['user_pk'])
        vendedor = User.objects.get(id=self.kwargs['user_pk'])
        print(vendedor)
        qs = self.model.objects.filter(arqueado=False, vendedor=vendedor)
        print(qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ArqueoSalidaListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = "Arqueo de Salida"
        return context


class ArqueoSalidaDetailView(DetailView):
    u"""Formulario para reingresar productos al almacen"""
    model = Salida
    pk_url_kwarg = 'salida_pk'
    template_name = "almacen/arqueo/salida_detail.html"

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ArqueoSalidaDetailView, self).get_context_data(**kwargs)
        detalles = SalidaDetalle.objects.filter(salida=self.get_object()).order_by("equipo__estado")
        context['title'] = "%s" % self.get_object().codigo
        context['opts'] = self.model._meta
        context['detalles'] = detalles
        return context

    def post(self, request, *args, **kwargs):
        imei = self.request.POST.get('imei')
        salida_pk = self.kwargs['salida_pk']

        try:
            salida_detalle = SalidaDetalle.objects.get(salida__id=salida_pk, equipo__imei=imei)
            if salida_detalle.equipo.estado == ALMACEN:
                messages.info(request, "Equipo ya se encuentra en almacen")
                return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

        except:
            messages.error(request, "Equipo no se encuentra en esta salida")
            return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

        equipo = salida_detalle.equipo

        equipo.estado = ALMACEN
        equipo.save()
        messages.success(self.request, "Equipo Ingresado a almacen")

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get_url_redirect(self, *args, **kwargs):

        return reverse("almacen:arqueo_salida_detail", kwargs={'salida_pk': self.kwargs['salida_pk']})


class ArqueoSalidaEquipoUpdateView(View):

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaEquipoUpdateView, self).dispatch(request, *args, **kwargs)

    def update(self, *args, **kwargs):
        salida_detalle = SalidaDetalle.objects.get(id=self.kwargs['salida_detalle_pk'])
        equipo = salida_detalle.equipo

        equipo.estado = ALMACEN
        equipo.save()
        messages.success(self.request, "Equipo de en almacen")

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get(self, *args, **kwargs):
        return self.update(*args, **kwargs)

    def get_url_redirect(self, *args, **kwargs):
        salida_detalle_id = self.kwargs['salida_detalle_pk']
        salida = Salida.objects.get(salidadetalle__id=salida_detalle_id)

        return reverse("almacen:arqueo_salida_detail", kwargs={'salida_pk': salida.id})


class ArqueoSalidaCerrar(View):

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaCerrar, self).dispatch(request, *args, **kwargs)

    def update(self, *args, **kwargs):
        salida = Salida.objects.get(id=self.kwargs['salida_pk'])
        self.vendedor = salida.vendedor

        salida_detalles = SalidaDetalle.objects.filter(salida=salida, equipo__estado=SALIDA)
        if salida_detalles:
            messages.error(self.request, "Tiene Equipos sin areglar")
            return HttpResponseRedirect(reverse("almacen:arqueo_salida_detail", kwargs={"salida_pk": salida.id}))

        else:
            salida.arqueado = True
            messages.success(self.request, "Salida Cerrada")
            salida.save()

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get(self, *args, **kwargs):
        return self.update(*args, **kwargs)

    def get_url_redirect(self, *args, **kwargs):
        return reverse("almacen:arqueo_salida_list", kwargs={'user_pk': self.vendedor.id})

apps/almacen/views/compra.py
from django.contrib import messages
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import BaseUpdateView

from apps.almacen.models.equipo import Equipo
from apps.compra.models.compra import Compra
from apps.compra.models.compra_detalle import CompraDetalle
from backend_apps.utils.decorators import permission_resource_required


class ComprobanteListView(ListView):
    u"""
    Lista de compras para almacen

    :url: /almacen/compra/listar
    :definicion: Lista las compras que aun no estan ingresadas a almacen
    """
    model = Compra
    template_name = "almacen/compra/list.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ComprobanteListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Compra.objects.filter(estado=False, procesado=True)
        for q in queryset:
            equipos = Equipo.objects.filter(compra_detalle__compra=q)
            cantidades = CompraDetalle.objects.filter(compra=q).aggregate(Sum('cantidad'))

            if cantidades['cantidad__sum'] == len(equipos):
                q.completado = True

        return queryset

    def get_context_data(self, **kwargs):
        context = super(ComprobanteListView, self).get_context_data(**kwargs)
        # verificar si ya esta ingresado

        context['opts'] = self.model._meta
        context['cmi'] = 'compra'
        context['title'] = ('Seleccione %s para Cambiar') % ('compra')
        return context


class CompraDetailView(DetailView):
    model = Compra
    template_name = "almacen/compra/detail.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CompraDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CompraDetailView, self).get_context_data(**kwargs)

        context['opts'] = self.model._meta
        context['cmi'] = 'compra detalle'
        context['title'] = "Agregar Compra Detalle"
        return context


class ComprobanteEstadoUpdateView(BaseUpdateView):
    """Acutaliza el estado de la compra para que ya este verificador completamente"""
    model = Compra
    fields = ['', ]
    success_url = reverse_lazy("almacen:compra_list")

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ComprobanteEstadoUpdateView, self).dispatch(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        """Acutaliza el estado de la compra para que ya este verificador completamente"""
        # validamos que todos los detalles esten completados
        comprobate = self.get_object()
        flag = True
        comprobate_detalles = CompraDetalle.objects.filter(compra=comprobate)
        for com_det in comprobate_detalles:
            if len(com_det.equipo_set.all()) != com_det.cantidad:
                flag = False

        if not flag:
            messages.error(request, "Aun no se completan los equipos")
            return HttpResponseRedirect(reverse("almacen:compra_detail", kwargs={'pk': comprobate.id}))
        comprobate.estado = True
        comprobate.save()
        messages.success(request, "Comprobaten totalmente ingresado")

        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

apps/almacen/views/usuario.py
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from apps.almacen.models.salida import Salida
from backend_apps.backend_auth.models import User
from backend_apps.utils.decorators import permission_resource_required

from backend_apps.backend_auth.constants import VENTA




class UserDetailView(DetailView):
    model = User
    template_name = "almacen/user/detail.html"

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(UserDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        salidas = Salida.objects.filter(vendedor=self.object)
        context['salidas'] = salidas
        return context

apps/almacen/templates/almacen/equipo/detail.html
{% extends "base/base_back.html" %}

{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

    <div>

        {% if equipo.producto.imagen %}
            <img src="{{ equipo.producto.imagen }}" alt="">
        {% endif %}

        <table class="table">
            <caption>Producto</caption>
            <tr>
                <th>Producto:</th>
                <td>{{ equipo.producto.codigo }}</td>
                <th>Color:</th>
                <td>{{ equipo.producto.color }}</td>
                <th>Marca:</th>
                <td>{{ equipo.producto.marca }}</td>
            </tr>


        </table>

        <table class="table">
            <caption>Equipo</caption>
            <tr>
                <th>Imei:</th>
                <td>{{ equipo.imei }}</td>
                <th>Contable:</th>
                <td>
                    {% if equipo.contable %}
                        <p class="text-info">
                            Contable
                        </p>
                    {% else %}
                        <p class="text-warning">No contable</p>
                    {% endif %}
                </td>
                <th>
                    Fecha de ingreso
                </th>
                <td>
                    {{ equipo.created_at|date:'d/m/Y H:i' }}
                </td>
                <th>Registrado por</th>
                <td>{{ equipo.user }}</td>
            </tr>

        </table>
        <div class="text-center">
            <div class="">
                <a href="{% url 'almacen:equipo_update' equipo.id %}" title="Actuilizar Equipo" class="btn btn-info"><i class="fa fa-edit"></i>Actualizar</a>

                <a href="{% url 'almacen:equipo_delete' equipo.pk %}"
                   class="btn btn-danger  js-confirm text-bold"
                   msg-title="Eliminar Equipo?."
                   msg="Esta Seguro<br/>Recuerde que esta acción no se puede retroceder"
                   title="Eliminar Equipo" rel="tooltip"><i
                        class="btn-icon-only fa fa-trash-o"></i> Eliminar</a>

            </div>
        </div>
    </div>

{% endblock content %}

apps/almacen/templates/almacen/equipo/list_menu.html
{% extends "base/base_back.html" %}

{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
    <script type="text/javascript">
        $(function () {
            $('table').kgrid({
                form_data: ['{{f}}', '{{q}}'],
                form_to: '{% url "almacen:equipo_list_menu" %}?f={{f}}&q={{q}}',
                order_attr: 'class=""',
                order_to: '{% url "almacen:equipo_list_menu" %}?f={{f}}&q={{q}}',
            });
        });
    </script>

    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>#</th>
                <th>Producto
                </th>
                <th class="col-hidden" data-search="imei"
                    data-order="imei">Imei
                </th>
                <th>
                    Estado
                </th>
                <th>
                    Fecha de Ingreso
                </th>
                <th>Registrado por</th>
                <th class="col-hidden" data-order="contable">Contable</th>

                <th class="btn-actions col-blocked text-center">Acción</th>
            </tr>
            </thead>
            <tbody>
            {% for d in object_list %}
                <tr>
                    <td>{% if is_paginated %}
                        {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                        {{ forloop.counter }}
                    {% endif %}
                    </td>
                    <td>{{ d.producto.codigo }}</td>
                    <td>{{ d.imei }}</td>
                    <td>{{ d.estado }}</td>
                    <td>
                    {{ d.created_at|date:'d/m/Y H:i' }}
                    </td>
                <td>
                    {{ d.user }}
                </td>
                    <td>
                        {% if d.contable %}
                            <p class="text-info">Contable</p>
                        {% else %}
                            <p class="text-warning">No Contable</p>
                        {% endif %}

                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <a href="{% url 'almacen:equipo_detail' d.pk %}"
                               class="btn btn-info btn-sm text-bold"
                               title="Cambiar Producto" rel="tooltip">
                                <i class="btn-icon-only fa fa-eye"></i>
                            </a>
                        </div>

                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="row">
        {% if is_paginated %}
            {% load paginator %}
            {% paginator %}
        {% else %}
            <div class="col-md-12">
                <ul class="breadcrumbpag">
                    {{ object_list.count }}
                    {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}
                        {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
                </ul>
            </div>
        {% endif %}
    </div>

{% endblock content %}

apps/almacen/templates/almacen/equipo/update.html
{% extends "base/base_back.html" %}

{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
    &rsaquo;
    <a href="{% url 'backend:menu_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

    {% crispy form %}

{% endblock %}


{% block customjs %}
    <script>
        $('form').submit(function () {
            $(this).find("button[type='submit']").prop('disabled', true);
        });
    </script>
{% endblock customjs %}