apps/almacen/urls.py
from django.conf.urls import url

from .views.arqueo import ArqueoSalidaListView, ArqueoListView, ArqueoSalidaDetailView, ArqueoSalidaEquipoUpdateView, \
    ArqueoSalidaCerrar
from .views.compra import ComprobanteListView, CompraDetailView, ComprobanteEstadoUpdateView
from .views.compra_detalle import CompraDetalleDetailView, CompraDetalleServiceView
from .views.equipo import EquiposAddServicioView, EquipoJson, EquipoMenuListView, \
    EquipoUpdateView, EquipoDetailView, EquipoDeleteView
from .views.usuario import UserDetailView
from .views.salida import SalidaCreateTemplateView, SalidaDetailView
from .views.producto import ProductoListView, ProductoDetailView, ProductoDetailCountAlmacenServiceView

urlpatterns = [

    # Menu
    url(r"^compra/listar$", ComprobanteListView.as_view(), name='compra_list'),
    url(r"^arqueo/listar$", ArqueoListView.as_view(), name='arqueo_list'),
    url(r"^salida/crear$", SalidaCreateTemplateView.as_view(), name='salida_add'),
    url(r"^producto/listar$", ProductoListView.as_view(), name='producto_list'),
    url(r"^equipo/listar$", EquipoMenuListView.as_view(), name='equipo_list_menu'),

    # Utils

    url(r"^usuario/detallar/(?P<pk>[^/]+)$", UserDetailView.as_view(), name='user_detail'),
    url(r"^salida/detallar/(?P<pk>[^/]+)$", SalidaDetailView.as_view(), name='salida_detail'),
    url(r"^producto/detallar/(?P<pk>[^/]+)$", ProductoDetailView.as_view(), name='producto_detail'),

    # administracion de equipo
    url(r"^equipo/detail/(?P<pk>[^/]+)$", EquipoDetailView.as_view(), name='equipo_detail'),
    url(r"^equipo/eliminar/(?P<pk>[^/]+)$", EquipoDeleteView.as_view(), name='equipo_delete'),
    url(r"^equipo/actualizar/(?P<pk>[^/]+)$", EquipoUpdateView.as_view(), name='equipo_update'),

    # compra
    url(r"^compra_detalle/detallar/(?P<pk>[^/]+)/(?P<producto_pk>[^/]+)$", CompraDetalleDetailView.as_view(),
        name='compra_detalle_detail'),
    url(r"^compra/detallar/(?P<pk>[^/]+)$", CompraDetailView.as_view(), name='compra_detail'),
    url(r"^compra/update_status/(?P<pk>[^/]+)$", ComprobanteEstadoUpdateView.as_view(), name='compra_updatestatus'),
    url(r"^compra_detalle/detailjson/$", CompraDetalleServiceView.as_view(), name='comra_detalle_detail_json'),

    # Arqueo
    url(r"^arqueo_salida/listar/(?P<user_pk>[^/]+)$", ArqueoSalidaListView.as_view(), name='arqueo_salida_list'),
    url(r"^arqueo_salida/detallar/(?P<salida_pk>[^/]+)$", ArqueoSalidaDetailView.as_view(),
        name='arqueo_salida_detail'),
    url(r"^arqueo_salida/cerrar/(?P<salida_pk>[^/]+)$", ArqueoSalidaCerrar.as_view(), name='arqueo_salida_close'),
    url(r"^arqueo_salida/equipo/(?P<salida_detalle_pk>[^/]+)$", ArqueoSalidaEquipoUpdateView.as_view(),
        name='arqueo_equipo_update'),

    # Service
    url(r"^equipo/add_service$", EquiposAddServicioView.as_view(), name='equipo_addservice'),
    url(r"^equipo/detail_json$", EquipoJson.as_view(), name='equipo_detail_json'),
    url(r"^producto/almacen_contar/(?P<pk>[^/]+)$", ProductoDetailCountAlmacenServiceView.as_view(),
        name='producto_detailservice'),

]

apps/compra/urls.py
from django.conf.urls import url

from .views.compra import (CompraCreateView, CompraDetailView, CompraPendienteListView, CompraProcesarView,
                           CompraUpdateView, CompraListView)
from .views.compra_detalle import CompraDetalleCreateView, CompraDetalleListView, CompraDetalleDeleteView
from .views.producto_general import ProductoGeneralAutocomplete
from .views.proveedor import ProveedorTemplateView, ProveedorAutocomplete

urlpatterns = [
    # Cargar Menu
    url('compra/crear$', CompraCreateView.as_view(), name='compra_add'),
    url('compra/pendientes$', CompraPendienteListView.as_view(), name='compra_slopes'),
    url('compra/listar$', CompraListView.as_view(), name='compra_list'),

    # No Menu
    url('compra/procesar/(?P<pk>[^/]+)', CompraProcesarView.as_view(), name='compra_process'),
    url('compra/actualizar/(?P<pk>[^/]+)', CompraUpdateView.as_view(), name='compra_update'),
    url('compra/detallar/(?P<pk>[^/]+)$', CompraDetailView.as_view(), name='compra_detail'),

    url('compra_detalle/crear/(?P<compra_pk>[^/]+)$', CompraDetalleCreateView.as_view(), name='compradetalle_add'),
    url('compra_detalle/listar/(?P<compra_pk>[^/]+)$', CompraDetalleListView.as_view(), name='compradetalle_list'),
    url('compra_detalle/eliminar/(?P<pk>[^/]+)/(?P<compra_pk>[^/]+)$', CompraDetalleDeleteView.as_view(),
        name='compradetalle_delete'),

    # Utils

    url('proveedor/view/$', ProveedorTemplateView.as_view(), name='proveedor_view'),
    # Autocompletes
    url('proveedor/autocomplete/', ProveedorAutocomplete.as_view(), name='proveedor_autocomplete'),
    url('producto/autocomplete/', ProductoGeneralAutocomplete.as_view(), name='producto_autocomplete')

]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from backend_apps.access.views import dashboard

from django.conf.urls.static import static
from qr_code import urls as qr_code_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),

    # Backend

    url(r'^backend/', include('backend_apps.backend_auth.urls', namespace='backend')),
    url(r'^access/', include('backend_apps.access.urls', namespace='access')),

    url(r'^$', dashboard, name='dashboard'),

    # My Apps
    url(r'^almacen/', include('apps.almacen.urls', namespace='almacen')),
    url(r'^compra/', include('apps.compra.urls', namespace='compra')),
    url(r'^persona/', include('apps.persona.urls', namespace='persona')),
    url(r'^producto/', include('apps.producto.urls', namespace='producto')),
    url(r'^sunat/', include('apps.sunat.urls', namespace='sunat')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^vendedor/', include('apps.vendedor.urls', namespace='vendedor')),
    url(r'^venta/', include('apps.venta.urls', namespace='venta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/almacen/models/equipo.py
from uuid import uuid4

from django.db import models

from apps.compra.models.compra_detalle import CompraDetalle
from apps.producto.models.producto import Producto
from backend_apps.backend_auth.models import User

from ..constants import ESTADO_EQUIPO_CHOICES, ALMACEN


class Equipo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    compra_detalle = models.ForeignKey(CompraDetalle, verbose_name=u"Compra Detalle", blank=True, null=True)
    imei = models.CharField(u"Imei", max_length=150, unique=True)
    producto = models.ForeignKey(Producto, verbose_name="Producto")
    estado = models.CharField(u"Estado", choices=ESTADO_EQUIPO_CHOICES, default=ALMACEN, max_length=15)
    contable = models.BooleanField(u"Contable", default=True)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(u"Created At", auto_now_add=True)
    updated_at = models.DateTimeField(u"Updated At", auto_now=True)

    class Meta:
        verbose_name = u"Equipo"
        verbose_name_plural = u"Equipos"

    def __str__(self):
        return "%s %s" % (self.producto, self.imei)

apps/compra/models/compra_detalle.py
from uuid import uuid4
from django.db import models

from apps.producto.models.producto import Producto
from apps.sunat.models.igv import Igv
from backend_apps.backend_auth.models import User
from .compra import Compra
from ...producto.models.producto_general import ProductoGeneral


class CompraDetalle(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    compra = models.ForeignKey(Compra, verbose_name=u"Compra")

    producto_general = models.ForeignKey(ProductoGeneral, verbose_name=u"Producto General", blank=True, null=True)
    cantidad = models.IntegerField(u"canidad")
    # monto del igv en procentaje actual esto va escondido
    igv = models.DecimalField(u"IGV", max_digits=5, decimal_places=2)
    valor_unitario = models.DecimalField(u"Valor Unitario", max_digits=5, decimal_places=2)

    precio_unitario = models.DecimalField(u"Precio Unitario", max_digits=5, decimal_places=2)

    igv_total = models.DecimalField(u"IGV", max_digits=5, decimal_places=2)
    precio_total = models.DecimalField(u"P. Total", max_digits=9, decimal_places=2)
    total = models.DecimalField(u"Total", max_digits=6, decimal_places=2)

    created_at = models.DateTimeField(u"Created at", auto_now_add=True)
    updated_at = models.DateTimeField(u"Updated at", auto_now=True)
    user = models.ForeignKey(User, verbose_name=u"User")

    class Meta:
        verbose_name = u"Compra Detalle"
        verbose_name_plural = u"Compra Detalles"
        ordering = ("created_at",)

    def __str__(self):
        return "%s %s" % (self.producto_general, self.total)

apps/almacen/views/arqueo.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, TemplateView
from django.views.generic.base import View

from apps.almacen.constants import SALIDA
from apps.almacen.models.equipo import Equipo
from apps.almacen.models.salida import Salida
from apps.almacen.models.salida_detalle import SalidaDetalle
from backend_apps.backend_auth.constants import VENTA, DISTRIBUIDOR, ALMACEN
from backend_apps.backend_auth.models import User
from backend_apps.utils.decorators import permission_resource_required


class ArqueoListView(ListView):
    u"""User List para arqueo"""
    model = User
    template_name = "almacen/arqueo/user_list.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        q = self.model.objects.filter(groups__name=DISTRIBUIDOR)

        return q

    def get_context_data(self, **kwargs):
        context = super(ArqueoListView, self).get_context_data(**kwargs)

        context['opts'] = self.model._meta
        context['cmi'] = 'Usuarios'
        context['title'] = 'Seleccione %s para agregar equipos' % 'Usuario'
        return context


class ArqueoSalidaListView(ListView):
    u"""Arque de de Equipos"""
    model = Salida
    template_name = "almacen/arqueo/salida_list.html"

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        print(self.kwargs['user_pk'])
        vendedor = User.objects.get(id=self.kwargs['user_pk'])
        print(vendedor)
        qs = self.model.objects.filter(arqueado=False, vendedor=vendedor)
        print(qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ArqueoSalidaListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['title'] = "Arqueo de Salida"
        return context


class ArqueoSalidaDetailView(DetailView):
    u"""Formulario para reingresar productos al almacen"""
    model = Salida
    pk_url_kwarg = 'salida_pk'
    template_name = "almacen/arqueo/salida_detail.html"

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ArqueoSalidaDetailView, self).get_context_data(**kwargs)
        detalles = SalidaDetalle.objects.filter(salida=self.get_object()).order_by("equipo__estado")
        context['title'] = "%s" % self.get_object().codigo
        context['opts'] = self.model._meta
        context['detalles'] = detalles
        return context

    def post(self, request, *args, **kwargs):
        imei = self.request.POST.get('imei')
        salida_pk = self.kwargs['salida_pk']

        try:
            salida_detalle = SalidaDetalle.objects.get(salida__id=salida_pk, equipo__imei=imei)
            if salida_detalle.equipo.estado == ALMACEN:
                messages.info(request, "Equipo ya se encuentra en almacen")
                return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

        except:
            messages.error(request, "Equipo no se encuentra en esta salida")
            return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

        equipo = salida_detalle.equipo

        equipo.estado = ALMACEN
        equipo.save()
        messages.success(self.request, "Equipo Ingresado a almacen")

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get_url_redirect(self, *args, **kwargs):

        return reverse("almacen:arqueo_salida_detail", kwargs={'salida_pk': self.kwargs['salida_pk']})


class ArqueoSalidaEquipoUpdateView(View):

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaEquipoUpdateView, self).dispatch(request, *args, **kwargs)

    def update(self, *args, **kwargs):
        salida_detalle = SalidaDetalle.objects.get(id=self.kwargs['salida_detalle_pk'])
        equipo = salida_detalle.equipo

        equipo.estado = ALMACEN
        equipo.save()
        messages.success(self.request, "Equipo de en almacen")

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get(self, *args, **kwargs):
        return self.update(*args, **kwargs)

    def get_url_redirect(self, *args, **kwargs):
        salida_detalle_id = self.kwargs['salida_detalle_pk']
        salida = Salida.objects.get(salidadetalle__id=salida_detalle_id)

        return reverse("almacen:arqueo_salida_detail", kwargs={'salida_pk': salida.id})


class ArqueoSalidaCerrar(View):

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(ArqueoSalidaCerrar, self).dispatch(request, *args, **kwargs)

    def update(self, *args, **kwargs):
        salida = Salida.objects.get(id=self.kwargs['salida_pk'])
        self.vendedor = salida.vendedor

        salida_detalles = SalidaDetalle.objects.filter(salida=salida, equipo__estado=SALIDA)
        if salida_detalles:
            messages.error(self.request, "Tiene Equipos sin areglar")
            return HttpResponseRedirect(reverse("almacen:arqueo_salida_detail", kwargs={"salida_pk": salida.id}))

        else:
            salida.arqueado = True
            messages.success(self.request, "Salida Cerrada")
            salida.save()

        return HttpResponseRedirect(self.get_url_redirect(*args, **kwargs))

    def get(self, *args, **kwargs):
        return self.update(*args, **kwargs)

    def get_url_redirect(self, *args, **kwargs):
        return reverse("almacen:arqueo_salida_list", kwargs={'user_pk': self.vendedor.id})

apps/almacen/views/compra_detalle.py
import simplejson as json
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, DetailView

from apps.almacen.models.equipo import Equipo
from apps.compra.models.compra_detalle import CompraDetalle
from apps.producto.models.producto import Producto
from backend_apps.utils.decorators import permission_resource_required


class CompraDetalleDetailView(DetailView):
    template_name = "almacen/compra_detalle/detail.html"
    model = CompraDetalle

    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(CompraDetalleDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CompraDetalleDetailView, self).get_context_data(**kwargs)
        producto = Producto.objects.get(id=self.kwargs['producto_pk'])

        context['producto'] = producto
        context['opts'] = self.model._meta
        context['title'] = "Producto"
        return context


class CompraDetalleServiceView(DetailView):
    @method_decorator(permission_resource_required())
    def dispatch(self, request, *args, **kwargs):
        return super(CompraDetalleServiceView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        compra_detalle_id = self.request.GET.get("compra_detalle_id")
        compra_detalle = CompraDetalle.objects.get(id=compra_detalle_id)
        equipos = Equipo.objects.filter(compra_detalle=compra_detalle)
        equipos_dic = []
        for equipo in equipos:
            equipos_dic.append({
                "producto_codigo": equipo.producto.codigo,
                "imei": equipo.imei
            })
        registrados = len(equipos)

        data = {
            "registrados": registrados,
            "equipos": equipos_dic,
            "cantidad": compra_detalle.cantidad,
            "contable": compra_detalle.compra.contable

        }

        dump = json.dumps(data)
        print(dump)

        return HttpResponse(dump, status=200, content_type="application/json")

apps/almacen/templates/almacen/compra/detail.html
{% extends "base/base_back.html" %}

{% load i18n app_security %}
{% load l10n humanize %}


{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
    &rsaquo; <a href="{% url 'almacen:compra_list' %}">Comprobantes</a>
    &rsaquo; {{ object.serie_comprobante }} - {{ compra.nro_comprobante }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
    <div class="container-overflow">
        <table class="table  table-hover table-striped table-condensed table-responsive">

            <tr>
                <th>Proveedor</th>
                <td>{{ object.proveedor }}</td>
                <th>
                    Fecha Registro
                </th>
                <td><label class="label label-info"><i
                        class="fa fa-calendar"></i></label> {{ object.created_at|date:'d/m/Y H:i' }}</td>
            </tr>
            <tr>
                <th>Identificación</th>
                <td>{{ object.proveedor.nro_documento }}</td>
                <th>Fecha Compra</th>
                <td><label class="label label-info"><i
                        class="fa fa-calendar"></i></label> {{ object.fecha_emision|date:"d/m/Y" }}</td>
            </tr>
            <tr>
                <th>Nro Doc</th>
                <td>{{ object.nro_comprobante }}</td>
                <th>Tipo Comprobante</th>
                <td>{{ object.tipo_comprobante }}</td>

            </tr>
        </table>
    </div>
    <div class="text-center">
        <a href="{% url 'almacen:compra_updatestatus' object.id %}"
           class="btn btn-success js-confirm" msg-title="Cerrar Comprobante" msg="Recuerde que no se puede revertir"
           title="Cerrar Comprobante">
            Finalizar
        </a>
    </div>
    <div class="container-overflow">
        <table class="table  table-hover table-striped table-condensed table-responsive">
            <caption>Detalle</caption>
            <tr>
                <th>#</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Imagen</th>
                <th>Acción</th>
            </tr>
            {% for d  in object.compradetalle_set.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ d.producto_general }}</td>
                    <td>{{ d.cantidad }}</td>
                    <td>
                        <button><img src="{{ d.imagen.url }}" width="50" alt=""></button>
                    </td>
                    <td>
                        {% if d.cantidad > d.equipo_set.count %}

                            <ul>
                                {% for producto in d.producto_general.producto_set.all %}
                                    <li>
                                        <a href="{% url 'almacen:compra_detalle_detail' d.pk producto.pk %}"><i
                                                class="fa fa-eye"></i> {{ producto.codigo }}</a>
                                    </li>
                                {% endfor %}

                            </ul>

                        {% else %}
                            <label class="label label-warning">
                                <i class="text-danger fa fa-compass"></i> Completado
                            </label>

                        {% endif %}


                    </td>
                </tr>

            {% endfor %}

        </table>

    </div>

    <div id="form_data_id">

    </div>


{% endblock content %}

apps/almacen/templates/almacen/compra/list.html
{% extends "base/base_back.html" %}


{% load i18n app_security %}
{% load l10n humanize %}


{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">Inicio</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}


{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}


{% block content %}
    <script type="text/javascript">
        $(function () {
            $('table').kgrid({
                form_data: ['{{f}}', '{{q}}'],
                form_to: '{% url "almacen:compra_list" %}?f={{f}}&q={{q}}',
                order_attr: 'class=""',
                order_to: '{% url "almacen:compra_list" %}?f={{f}}&q={{q}}',
            });
        });
    </script>

    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th class="col-hidden" data-search="nro_correlativo"
                    data-order="nro_correlativo">Nro.
                </th>
                <th class="col-hidden">Nro. Comprobante</th>
                <th class="col-hidden" data-search="proveedor"
                    data-order="proveedor">Proveedor
                </th>

                <th class="col-hidden">Fecha de Compra</th>
                <th class="col-hidden">Fecha de Ingreso</th>

                <th class="btn-actions col-blocked text-center">Acción</th>
            </tr>
            </thead>
            <tbody>
            {% for d in object_list %}
                <tr class="{{ d.completado|yesno:',danger' }}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ d.nro_comprobante }}</td>
                    <td>{{ d.proveedor.razon_social }}</td>

                    <td>{{ d.fecha_emision }}</td>
                    <td>{{ d.created_at }}</td>


                    <td class="text-center">
                        <div class="btn-group">
                            <a href="{% url 'almacen:compra_detail' d.pk %}"
                               class="btn btn-info btn-sm text-bold"
                               title="Detalle Compra" rel="tooltip">
                                <i class="btn-icon-only fa fa-eye"></i>
                            </a>
                        </div>

                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="row">
        {% if is_paginated %}
            {% load paginator %}
            {% paginator %}
        {% else %}
            <div class="col-md-12">
                <ul class="breadcrumbpag">
                    {{ object_list.count }}
                    {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}
                        {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
                </ul>
            </div>
        {% endif %}
    </div>

{% endblock content %}